apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.50.0

#! Rebase rules explicitly define how kapp should merge resources during an update.
#! See more about the resource merge method: https://carvel.dev/kapp/docs/latest/merge-method.
rebaseRules:

  - path: [spec, caBundle]
    type: remove
    resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: apiregistration.k8s.io/v1, kind: APIService}
  - path: [ spec, selector, matchLabels, kapp.k14s.io/app ]
    type: copy
    sources: [ existing ]
    resourceMatchers:
      - apiVersionKindMatcher: { apiVersion: apps/v1, kind: Deployment }
