apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: metrics-server.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: metrics-server.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-metrics-server/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: metrics-server.packages.kadras.io
spec:
  categories:
  - monitoring
  - metrics
  - observability
  displayName: metrics-server
  longDescription: Metrics Server is a scalable and efficient source of container
    resource metrics for Kubernetes built-in autoscaling pipelines.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Scalable and efficient source of container resource metrics for
    Kubernetes built-in autoscaling pipelines.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-metrics-server
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: metrics-server
spec:
  packageRef:
    refName: metrics-server.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
